name: Build IOS

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    env:
      APP_NAME: "Student App"  # Set the app name here

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          
      - run: flutter pub get
      

      - run: pod repo update
        working-directory: ios

      - run: flutter build ios --release --no-codesign

      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - name: Zip output with dynamic name
        run: zip -qq -r -9 "${{ env.APP_NAME }}.ipa" Payload
        working-directory: build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/${{ env.APP_NAME }}.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first release"
